# ============================================================
# Enterprise Infrastructure & Automation Lab
# Sanitized Ansible Inventory Example
# ============================================================

[linux]
linux-server-01 ansible_host=10.10.10.11
linux-server-02 ansible_host=10.10.10.12

[windows]
windows-server-01 ansible_host=10.10.20.11

[network]
network-device-01 ansible_host=10.10.30.1
firewall-01 ansible_host=10.10.30.254

[monitoring]
zabbix-01 ansible_host=10.10.40.10

[virtualization]
hypervisor-01 ansible_host=10.10.50.10

[security]
security-server-01 ansible_host=10.10.60.10


# ============================================================
# Parent Groups
# ============================================================

[enterprise:children]
linux
windows
network
monitoring
virtualization
security
